### ISSUE TITLE
Add option to run the e2e test on s3proxy

### ISSUE THREAD

**Issue by jbygdell** [NBISweden/LocalEGA-tester#32]
### Description

When the s3proxy is ready we need to add it to the tester
### Proposed solution

Run the e2e tester against the deployed inbox solution .
Since we now have a way of knowing which inbox is deployed we can run the tests selectively.
### Definition of Done

e2e-test run against the s3proxy

**Comment by jbygdell** [comment]
Closed via #35

**Comment by blankdots** [comment]
Fixed in #35 and #33
